catalog:
  descriptor:
    name: "ICICI Bank"

  providers:
    - id: "PROVIDER_ID_personal_loan"
      descriptor:
        name: "ICICI Bank"
        short_desc: "ICICI Bank Ltd"
        long_desc: "ICICI Bank Ltd, India."
        images:
          - url: "https://www.icicibank.com/content/dam/icicibank/india/assets/images/header/logo.png"
            size_type: "sm"

      categories:
        - id: "101123"
          descriptor:
            code: "PERSONAL_LOAN"
            name: "Personal Loan"

        - id: "101124"
          parent_category_id: "101123"
          descriptor:
            code: "BUREAU_LOAN"
            name: "Bureau Loan"

        - id: "101125"
          parent_category_id: "101123"
          descriptor:
            code: "AA_PERSONAL_LOAN"
            name: "Account Aggregator Loan"

      items:
        - id: "ITEM_ID_PERSONAL_LOAN_2"
          descriptor:
            code: "PERSONAL_LOAN"
            name: "Personal Loan with AA"
          category_ids:
            - "101123"
            - "101125"
          matched: true
          recommended: true
          tags:
            - descriptor:
                code: "GENERAL_INFO"
                name: "General Information"
              display: true
              list:
                - descriptor:
                    code: "MIN_INTEREST_RATE"
                    name: "Minimum Interest Rate"
                    short_desc: "Loans starting from 9% (p.a)"
                  value: "9%"
                - descriptor:
                    code: "MAX_INTEREST_RATE"
                    name: "Maximum Interest Rate"
                    short_desc: "Loan Rate below from 15% (p.a)"
                  value: "15%"
                - descriptor:
                    code: "MIN_TENURE"
                    name: "Minimum Tenure"
                    short_desc: "Loan Tenure starting form 5 months"
                  value: "5 months"
                - descriptor:
                    code: "MAX_TENURE"
                    name: "Maximum Tenure"
                    short_desc: "Loan Tenure upto form 5 years"
                  value: "5 years"
                - descriptor:
                    code: "MIN_LOAN_AMOUNT"
                    name: "Minimum Loan Amount"
                    short_desc: "Loan Amount starting from 50,000"
                  value: "50000"
                - descriptor:
                    code: "MAX_LOAN_AMOUNT"
                    name: "Minimum Loan Amount"
                    short_desc: "Loan Amount upto form 50,00,000"
                  value: "5000000"

          xinput:
            head:
              descriptor:
                name: "Customer Information"
              index:
                min: 0
                cur: 0
                max: 0
              headings:
                - "Personal Information"
            form:
              id: "F01"
              mime_type: "text/html"
              url: "https://bpp.credit.becknprotocol.org/xinput/formid/F01"
              resubmit: false
              multiple_sumbissions: false
            required: true

      payments:
        - collected_by: "BPP"
          tags:
            - descriptor:
                code: "BUYER_FINDER_FEES"
              display: false
              list:
                - descriptor:
                    code: "BUYER_FINDER_FEES_TYPE"
                  value: "PERCENT_ANNUALIZED"
                - descriptor:
                    code: "BUYER_FINDER_FEES_PERCENTAGE"
                  value: "1"

            - descriptor:
                code: "SETTLEMENT_TERMS"
              display: false
              list:
                - descriptor:
                    code: "SETTLEMENT_WINDOW"
                  value: "PT30D"
                - descriptor:
                    code: "SETTLEMENT_BASIS"
                  value: "INVOICE_RECEIPT"
                - descriptor:
                    code: "MANDATORY_ARBITRATION"
                  value: "TRUE"
                - descriptor:
                    code: "COURT_JURISDICTION"
                  value: "New Delhi"
                - descriptor:
                    code: "STATIC_TERMS"
                  value: "https://bpp.credit.becknprotocol.org/personal-banking/loans/personal-loan"
                - descriptor:
                    code: "OFFLINE_CONTRACT"
                  value: "true"

      tags:
        - descriptor:
            code: "CONTACT_INFO"
            name: "Contact Info"
          list:
            - descriptor:
                code: "GRO_NAME"
              value: "ICICI"
            - descriptor:
                code: "GRO_EMAIL"
              value: "lifeline@iciciprulife.com"
            - descriptor:
                code: "GRO_CONTACT_NUMBER"
              value: "1860 266 7766"
            - descriptor:
                code: "CUSTOMER_SUPPORT_LINK"
              value: "https://buy.iciciprulife.com/buy/GrievanceRedStep.htm?execution=e1s1"
            - descriptor:
                code: "CUSTOMER_SUPPORT_CONTACT_NUMBER"
              value: "1800 1080"
            - descriptor:
                code: "CUSTOMER_SUPPORT_EMAIL"
              value: "customer.care@icicibank.com"

        - descriptor:
            code: "LSP_INFO"
            name: "Lsp Info"
          list:
            - descriptor:
                code: "LSP_NAME"
              value: "ICICI_LSP"
            - descriptor:
                code: "LSP_EMAIL"
              value: "lsp@iciciprulife.com"
            - descriptor:
                code: "LSP_CONTACT_NUMBER"
              value: "1860 266 7766"
            - descriptor:
                code: "LSP_ADDRESS"
              value: "One Indiabulls centre, Tower 1, 18th Floor Jupiter mill compound 841, Senapati Bapat Marg, Elphinstone Road, Mumbai 400013"
