order:
  provider:
    id: "P1"
    descriptor:
      name: "ABC Insurance Ltd."
      short_desc: "ABC Insurance Ltd. India "
      long_desc: "ABC Insurance Ltd. Deals in multiple Insurance Services like Health, Motor, Marine etc"
      images:
        - url: "https://www.abcinsurance.com/content/dam/abc/india/assets/images/header/logo.png"
          size_type: "xs"

  fulfillments:
    - id: "F1"
      type: "POLICY"
      customer:
        contact:
          email: "joe.adam@abc.org"
          phone: "+91-9999999999"

  items:
    - id: "CHILD_ITEM_ID_I1"
      parent_item_id: "I1"
      category_ids:
        - "C1"
        - "C3"
      descriptor:
        name: "Health Gain Plus Individual"
        short_desc: "ABC Individaul Health Insurance Class A with custom addon"
      price:
        currency: "INR"
        value: "900"
      tags:
        - descriptor:
            name: "General Information"
            code: "GENERAL_INFO"
          list:
            - descriptor:
                code: "COVERAGE_AMOUNT"
              value: "10000000"
            - descriptor:
                code: "CO_PAYMENT"
              value: "Yes"
            - descriptor:
                code: "ROOM_RENT_CAP"
              value: "25000"
            - descriptor:
                code: "RESTORATION_BENEFIT"
              value: "No"
            - descriptor:
                code: "CLAIM_SETTLEMENT_RATIO"
              value: "0.8"
            - descriptor:
                code: "PRE_HOSPITALIZATION_COVERAGE_DAYS"
              value: "2"
            - descriptor:
                code: "POST_HOSPITALIZATION_COVERAGE_DAYS"
              value: "5"
            - descriptor:
                code: "MATERNITY_COVERAGE"
              value: "Yes"
            - descriptor:
                code: "INITIAL_WAITING_PERIOD"
              value: "No"
            - descriptor:
                code: "CASHLESS_HOSPITALS"
              value: "50"
            - descriptor:
                code: "ROOM_CATEGORY"
              value: "Deluxe"
            - descriptor:
                code: "PROPOSAL_ID"
              value: "PROPOSAL_ID"
      time:
        duration: "P1Y"
        label: "TENURE"
      xinput:
        head:
          descriptor:
            name: "CIS"
          index:
            min: 0
            cur: 2
            max: 2
          headings:
            - "PROPOSER_DETAILS"
            - "NOMINEE_DETAILS"
            - "CIS"
        form:
          id: "FO8"
          mime_type: "application/html"
          url: "https://fis.test.bpp.io/form/nominee_dtls?formid=FO8"
          resubmit: true
          multiple_sumbissions: false
        required: true
      add_ons:
        - id: "A1"
          quantity:
            selected:
              count: 1
          descriptor:
            name: "No Claim Bonus"
            code: "NO_CLAIM_BONUS"
          price:
            value: "100"
            currency: "INR"
          tags:
            - descriptor:
                name: "Info"
                code: "INFO"
              list:
                - descriptor:
                    code: "REQUIRED"
                  value: "TRUE"
                - descriptor:
                    code: "CUSTOMER_SELECTION"
                  value: "YES"
                - descriptor:
                    code: "SUM_INSURED"
                  value: "50000"
                - descriptor:
                    code: "NOMINEE_DETAILS"
                    short_desc: "Describes the format as 'Salutation | First Name | Middle Name | Last Name | Relationship | Contact Number' represents a full name structure, where the values are separated by a pipe (|) symbol"
                  value: "Mr. | Joe | Wick | Adams | Son | +91-9988776655"

  payments:
    - collected_by: "BPP"
      status: "NOT-PAID"
      type: "PRE-FULFILLMENT"
      params:
        bank_account_number: "1800002341"
        bank_code: "SBIN0001234"
        currency: "INR"
      tags:
        - descriptor:
            code: "BUYER_FINDER_FEES"
          display: false
          list:
            - descriptor:
                code: "BUYER_FINDER_FEES_TYPE"
              value: "percent-annualized"
            - descriptor:
                code: "BUYER_FINDER_FEES_PERCENTAGE"
              value: "1"
        - descriptor:
            code: "SETTLEMENT_TERMS"
          display: false
          list:
            - descriptor:
                code: "SETTLEMENT_WINDOW"
              value: "PT60M"
            - descriptor:
                code: "SETTLEMENT_BASIS"
              value: "Delivery"
            - descriptor:
                code: "SETTLEMENT_TYPE"
              value: "upi"
            - descriptor:
                code: "MANDATORY_ARBITRATION"
              value: "true"
            - descriptor:
                code: "COURT_JURISDICTION"
              value: "New Delhi"
            - descriptor:
                code: "DELAY_INTEREST"
              value: "2.5"
            - descriptor:
                code: "STATIC_TERMS"
              value: "https://www.icicibank.com/personal-banking/loans/personal-loan"
            - descriptor:
                code: "SETTLEMENT_AMOUNT"
              value: "1000"
            - descriptor:
                code: "OFFLINE_CONTRACT"
              value: "true"

  quote:
    id: "OFFER_ID/PROPOSAL_ID"
    price:
      currency: "INR"
      value: "1100"
    ttl: "P15D"
    breakup:
      - title: "BASE_PRICE"
        price:
          value: "900"
          currency: "INR"
      - title: "CONVIENCE_FEE"
        price:
          value: "50"
          currency: "INR"
      - title: "TAX"
        price:
          value: "40"
          currency: "INR"
      - title: "PROCESSING_FEE"
        price:
          value: "10"
          currency: "INR"
      - title: "ADD_ONS"
        item:
          id: "CHILD_ITEM_ID_I1"
          add_ons:
            - id: "A1"
        price:
          value: "100"
          currency: "INR"

  cancellation_terms:
    - external_ref:
        mimetype: "text/html,"
        url: "https://fis.test.bpp.io/cancellation-terms"
