order:
  items:
    - id: CHILD_ITEM_CI1
      parent_item_id: I1
      add_ons:
        - id: A1
          quantity:
            selected:
              count: 1
          tags:
            - descriptor:
                name: BAP Inputs
                code: BAP_INPUTS
              list:
                - descriptor:
                    code: SUM_INSURED
                  value: "50000"
                - descriptor:
                    code: NOMINEE_DETAILS
                    short_desc: >-
                      Describes the format as 'Salutation | First Name | Middle Name |
                      Last Name | Relationship | Contact Number' represents a full name
                      structure, where the values are separated by a pipe (|) symbol
                  value: "Mr. | Joe | Wick | Adams | Son | +91-9988776655"
      tags:
        - descriptor:
            name: General Information
            code: GENERAL_INFO
          list:
            - descriptor:
                code: IDV_SELECTED
              value: "300000"
  provider:
    id: P1
