order:
  items:
    - id: "CHILD_ITEM_CI1"
      parent_item_id: "I1"
      add_ons:
        - id: "A1"
          quantity:
            selected:
              count: 1
      xinput:
        form:
          id: "F04"
        form_response:
          status: "SUCCESS"
          submission_id: "a4db048b-d07c-40e0-9c0b-b7f006c4df74"
  provider:
    id: "P1"
