codes:
  - code: 200
    action_id: search
    action: search
    default: FIS12/gold-loan/2.0.2/search/default.yaml
    message_id: true
  - code: 201
    action_id: on_search
    action: on_search
    default: FIS12/gold-loan/2.0.2/on_search/default.yaml
    message_id: false
  - code: 202
    action_id: select_adjust_loan_amount
    action: select
    default: FIS12/gold-loan/2.0.2/select_adjust_loan_amount/default.yaml
    message_id: true
  - code: 2021
    action_id: select_1
    action: select
    default: FIS12/gold-loan/2.0.2/select_1/default.yaml
    message_id: true
  - code: 2022
    action_id: select_2
    action: select
    default: FIS12/gold-loan/2.0.2/select_2/default.yaml
    message_id: true
  - code: 203
    action_id: on_select_adjust_loan_amount
    action: on_select
    default: FIS12/gold-loan/2.0.2/on_select_adjust_loan_amount/default.yaml
    message_id: false
  - code: 2031
    action_id: on_select_1
    action: on_select
    default: FIS12/gold-loan/2.0.2/on_select_1/default.yaml
    message_id: false
  - code: 2032
    action_id: on_select_2
    action: on_select
    default: FIS12/gold-loan/2.0.2/on_select_2/default.yaml
    message_id: false
  - code: 204
    action_id: init
    action: init
    default: FIS12/gold-loan/2.0.2/init/default.yaml
    message_id: true
  - code: 205
    action_id: on_init
    action: on_init
    default: FIS12/gold-loan/2.0.2/on_init/default.yaml
    message_id: false
  - code: 206
    action_id: confirm
    action: confirm
    default: FIS12/gold-loan/2.0.2/confirm/default.yaml
    message_id: true
  - code: 207
    action_id: on_confirm
    action: on_confirm
    default: FIS12/gold-loan/2.0.2/on_confirm/default.yaml
    message_id: false
  - code: 208
    action_id: update
    action: update
    default: FIS12/gold-loan/2.0.2/update/default.yaml
    message_id: true
  - code: 209
    action_id: on_update
    action: on_update
    default: FIS12/gold-loan/2.0.2/on_update/default.yaml
    message_id: false 
  - code: 210
    action_id: on_update_unsolicited
    action: on_update
    default: FIS12/gold-loan/2.0.2/on_update_unsolicited/default.yaml
    message_id: true
  - code: 211
    action_id: status
    action: status
    default: FIS12/gold-loan/2.0.2/status/default.yaml
    message_id: true
  - code: 212
    action_id: on_status
    action: on_status
    default: FIS12/gold-loan/2.0.2/on_status/default.yaml
    message_id: false
  - code: 213
    action_id: on_status_unsolicited
    action: on_status
    default: FIS12/gold-loan/2.0.2/on_status_unsolicited/default.yaml
    message_id: true

  # Personal Loan actions
  - code: 300
    action_id: search_personal_loan
    action: search
    default: FIS12/personal-loan/2.0.2/search/default.yaml
    message_id: true
  - code: 301
    action_id: on_search_personal_loan
    action: on_search
    default: FIS12/personal-loan/2.0.2/on_search/default.yaml
    message_id: false
  - code: 302
    action_id: select_bureau_consent_personal_loan
    action: select
    default: FIS12/personal-loan/2.0.2/select_bureau_consent_personal_loan/default.yaml
    message_id: true
  - code: 303
    action_id: on_select_bureau_consent_personal_loan
    action: on_select
    default: FIS12/personal-loan/2.0.2/on_select_bureau_consent_personal_loan/default.yaml
    message_id: false
  - code: 3021
    action_id: select_1_personal_loan
    action: select
    default: FIS12/personal-loan/2.0.2/select_1/default.yaml
    message_id: true
  - code: 3022
    action_id: select_2_personal_loan
    action: select
    default: FIS12/personal-loan/2.0.2/select_2/default.yaml
    message_id: true
  - code: 3031
    action_id: on_select_1_personal_loan
    action: on_select
    default: FIS12/personal-loan/2.0.2/on_select_1/default.yaml
    message_id: false
  - code: 3032
    action_id: on_select_2_personal_loan
    action: on_select
    default: FIS12/personal-loan/2.0.2/on_select_2/default.yaml
    message_id: false
  - code: 304
    action_id: init_personal_loan
    action: init
    default: FIS12/personal-loan/2.0.2/init/default.yaml
    message_id: true
  - code: 305
    action_id: on_init_personal_loan
    action: on_init
    default: FIS12/personal-loan/2.0.2/on_init/default.yaml
    message_id: false
  - code: 306
    action_id: confirm_personal_loan
    action: confirm
    default: FIS12/personal-loan/2.0.2/confirm/default.yaml
    message_id: true
  - code: 307
    action_id: on_confirm_personal_loan
    action: on_confirm
    default: FIS12/personal-loan/2.0.2/on_confirm/default.yaml
    message_id: false
  - code: 308
    action_id: update_personal_loan
    action: update
    default: FIS12/personal-loan/2.0.2/update/default.yaml
    message_id: true
  - code: 309
    action_id: on_update_personal_loan
    action: on_update
    default: FIS12/personal-loan/2.0.2/on_update/default.yaml
    message_id: false
  - code: 310
    action_id: on_update_unsolicited_personal_loan
    action: on_update
    default: FIS12/personal-loan/2.0.2/on_update_unsolicited/default.yaml
    message_id: true
  - code: 311
    action_id: status_personal_loan
    action: status
    default: FIS12/personal-loan/2.0.2/status/default.yaml
    message_id: true
  - code: 312
    action_id: on_status_personal_loan
    action: on_status
    default: FIS12/personal-loan/2.0.2/on_status/default.yaml
    message_id: false
  - code: 313
    action_id: on_status_unsolicited_personal_loan
    action: on_status
    default: FIS12/personal-loan/2.0.2/on_status_unsolicited/default.yaml
    message_id: true
  - code: 3041
    action_id: init_1_personal_loan
    action: init
    default: FIS12/personal-loan/2.0.2/init_1/default.yaml
    message_id: true
  - code: 3042
    action_id: init_2_personal_loan
    action: init
    default: FIS12/personal-loan/2.0.2/init_2/default.yaml
    message_id: true
  - code: 3043
    action_id: init_3_personal_loan
    action: init
    default: FIS12/personal-loan/2.0.2/init_3/default.yaml
    message_id: true
  - code: 3051
    action_id: on_init_1_personal_loan
    action: on_init
    default: FIS12/personal-loan/2.0.2/on_init_1/default.yaml
    message_id: false
  - code: 3052
    action_id: on_init_2_personal_loan
    action: on_init
    default: FIS12/personal-loan/2.0.2/on_init_2/default.yaml
    message_id: false
  - code: 3053
    action_id: on_init_3_personal_loan
    action: on_init
    default: FIS12/personal-loan/2.0.2/on_init_3/default.yaml
    message_id: false
  - code: 3023
    action_id: select_3_personal_loan
    action: select
    default: FIS12/personal-loan/2.0.2/select_3/default.yaml
    message_id: true
  - code: 3033
    action_id: on_select_3_personal_loan
    action: on_select
    default: FIS12/personal-loan/2.0.2/on_select_3/default.yaml
    message_id: false
  - code: 3054
    action_id: init_offline_personal_loan
    action: init
    default: FIS12/personal-loan/2.0.2/init_offline/default.yaml
    message_id: true
  - code: 3055
    action_id: on_init_offline_personal_loan
    action: on_init
    default: FIS12/personal-loan/2.0.2/on_init_offline_personal_loan/default.yaml
    message_id: false
  - code: 3056
    action_id: init_offline_and_online_personal_loan
    action: init
    default: FIS12/personal-loan/2.0.2/init_offline_and_online_personal_loan/default.yaml
    message_id: true
  - code: 3057
    action_id: on_init_offline_and_online_personal_loan
    action: on_init
    default: FIS12/personal-loan/2.0.2/on_init_offline_and_online_personal_loan/default.yaml
    message_id: false
  - code: 3111
    action_id: status_1_personal_loan
    action: status
    default: FIS12/personal-loan/2.0.2/status_1/default.yaml
    message_id: true
  - code: 3121
    action_id: on_status_1_personal_loan
    action: on_status
    default: FIS12/personal-loan/2.0.2/on_status_1/default.yaml
    message_id: false
  - code: 314
    action_id: update_personal_loan_fulfillment
    action: update
    default: FIS12/personal-loan/2.0.2/update_personal_loan_fulfillment/default.yaml
    message_id: true
  - code: 315
    action_id: on_update_personal_loan_fulfillment
    action: on_update
    default: FIS12/personal-loan/2.0.2/on_update_personal_loan_fulfillment/default.yaml
    message_id: false