catalog:
  descriptor:
    name: "ABC Insurance Ltd"
  providers:
    - id: "P1"
      descriptor:
        name: "ABC Insurance Ltd."
        short_desc: "ABC Insurance Ltd. India"
        long_desc: "ABC Insurance Ltd. Deals in multiple Insurance Services like Health, Motor, Marine etc"
        images:
          - url: "https://www.abcinsurance.com/content/dam/abc/india/assets/images/header/logo.png"
            size_type: "xs"
      categories:
        - id: "C1"
          descriptor:
            name: "Individual Insurance"
            code: "INDIVIDUAL_INSURANCE"
        - id: "C2"
          descriptor:
            name: "Family Insurance"
            code: "FAMILY_INSURANCE"
        - id: "C3"
          descriptor:
            name: "Health Insurance"
            code: "HEALTH_INSURANCE"
      items:
        - category_ids:
            - C2
            - C3
          descriptor:
            name: Health Gain Plus Family
            short_desc: short description of the Family Insurance Type 1
          id: 1b0fb502-630d-4650-a195-9262c1436e2d
          tags:
            - descriptor:
                name: General Information
                code: GENERAL_INFO
              list:
                - descriptor:
                    code: COVERAGE_AMOUNT
                  value: "10000000"
                - descriptor:
                    code: CO_PAYMENT
                  value: "Yes"
                - descriptor:
                    code: ROOM_RENT_CAP
                  value: "25000"
                - descriptor:
                    code: RESTORATION_BENEFIT
                  value: "No"
                - descriptor:
                    code: CLAIM_SETTLEMENT_RATIO
                  value: "0.8"
                - descriptor:
                    code: PRE_HOSPITALIZATION_COVERAGE_DAYS
                  value: "2"
                - descriptor:
                    code: POST_HOSPITALIZATION_COVERAGE_DAYS
                  value: "5"
                - descriptor:
                    code: MATERNITY_COVERAGE
                  value: "Yes"
                - descriptor:
                    code: INITIAL_WAITING_PERIOD
                  value: "No"
                - descriptor:
                    code: CASHLESS_HOSPITALS
                  value: "50"
                - descriptor:
                    code: ROOM_CATEGORY
                  value: Deluxe
          add_ons:
            - id: C1
              quantity:
                available:
                  count: 1
              descriptor:
                name: No Claim Bonus
                code: NO_CLAIM_BONUS
            - id: C2
              quantity:
                available:
                  count: 1
              descriptor:
                name: Daycare Cover
                code: DAYCARE_COVER
            - id: C3
              quantity:
                available:
                  count: 1
              descriptor:
                name: Daily Cash Allowance
                code: DAILY_CASH_ALLOWANCE
            - id: "4"
              quantity:
                available:
                  count: 1
              descriptor:
                name: Domicialiary Expenses
                code: DOMICILIARY_EXPENSES
            - id: "5"
              quantity:
                available:
                  count: 1
              descriptor:
                name: Health Check-ups
                code: HEALTH_CHECK_UPS
          time:
            duration: P1Y
            label: TENURE
          xinput:
            head:
              descriptor:
                name: Customer Information
              index:
                min: 0
                cur: 0
                max: 0
              headings:
                - INSURED_PERSONAL_DETAILS
            form:
              id: FO2
              mime_type: text/html
              url: https://fis.test.bpp.io/form/family_dtls?formId=FO2
              resubmit: true
              multiple_sumbissions: false
            required: true
