order:
  provider:
    id: "101"
    descriptor:
      images:
        - url: "https://url.com/hdfc/hdfc-sm.png"
          size_type: "sm"
        - url: "https://url.com/hdfc/hdfc-md.png"
          size_type: "md"
        - url: "https://url.com/hdfc/hdfc-lg.png"
          size_type: "lg"
      name: "HDFC Bank Limited"
      short_desc: "HDFC Bank Limited"
      long_desc: "HDFC Bank Limited"

    tags:
      - descriptor:
          code: "CONTACT_INFO"
          name: "Contact Info"
        list:
          - descriptor:
              code: "GRO_NAME"
              name: "Gro name"
            value: "Rishav Singh"
          - descriptor:
              code: "GRO_EMAIL"
              name: "Gro email"
            value: "support@hdfcbank.com"
          - descriptor:
              code: "GRO_CONTACT_NUMBER"
              name: "Gro contact number"
            value: "18001600"
          - descriptor:
              code: "GRO_DESIGNATION"
              name: "Gro Designation"
            value: "Grievance Redressal Officer"
          - descriptor:
              code: "GRO_ADDRESS"
              name: "Gro Address"
            value: "Mumbai Maharashtra 400013"
          - descriptor:
              code: "CUSTOMER_SUPPORT_LINK"
              name: "Customer support link"
            value: "https://www.hdfcbank.com/personal/need-help/contact-us"
          - descriptor:
              code: "CUSTOMER_SUPPORT_CONTACT_NUMBER"
              name: "Customer support contact number"
            value: "18001600"
          - descriptor:
              code: "CUSTOMER_SUPPORT_EMAIL"
              name: "Customer support email"
            value: "loansupport@example.com"

      - descriptor:
          code: "LSP_INFO"
          name: "Lsp Info"
        list:
          - descriptor:
              code: "LSP_NAME"
              name: "Lsp name"
            value: "HDFC BANK LIMITED"
          - descriptor:
              code: "LSP_EMAIL"
              name: "Lsp email"
            value: "support@hdfcbank.com"
          - descriptor:
              code: "LSP_CONTACT_NUMBER"
              name: "Lsp contact number"
            value: "18001600"
          - descriptor:
              code: "LSP_ADDRESS"
              name: "Lsp Address"
            value: "Mumbai Maharashtra 400013"

  items:
    - id: "d9eb81e2-96b5-477f-98dc-8518ad60d72e"
      descriptor:
        code: "CREDIT_CARD"
        name: "HDFC Gold Credit Card"
        short_desc: "Experience the Golden Side Of Life"
        images:
          - url: "https://url.com/hdfc/cards/hdfc-sm.png"
            size_type: "sm"
          - url: "https://url.com/hdfc/cards/hdfc-md.png"
            size_type: "md"
          - url: "https://url.com/hdfc/cards/hdfc-lg.png"
            size_type: "lg"

      tags:
        - descriptor:
            name: "General Information"
            code: "GENERAL_INFO"
          display: true
          list:
            - descriptor:
                code: "WELCOME_BENEFIT"
                name: "Welcome Benefit"
                short_desc: "Welcome Benefit"
              value: "Complimentary Swiggy One and MMT Black Gold membership as Welcome benefits"
            - descriptor:
                code: "ANNUAL_FEE"
                name: "Annual Fee"
                short_desc: "Annual membership fee"
              value: "1000 INR"
            - descriptor:
                code: "JOINING_FEE"
                name: "Joining Fee"
                short_desc: "One-time joining fee"
              value: "500 INR"
            - descriptor:
                code: "REWARDS"
                name: "Rewards"
                short_desc: "Reward points earned on spent"
              value: "2 Points per ₹150 spent"
            - descriptor:
                code: "TRAVEL_BENEFITS"
                name: "Travel Benefits"
                short_desc: "Travel Benefits"
              value: "- 2 Points per ₹150 spent on MMT,\n - 2 Points per ₹150 spent on others"
            - descriptor:
                code: "LIFESTYLE_BENEFITS"
                name: "Lifestyle Benefits"
                short_desc: "Lifestyle Benefits"
              value: "Enjoy the exclusive 24/7 Concierge Services on your HDFC Bank Regalia Gold Credit Card."
            - descriptor:
                code: "EVERYDAY_BENEFITS"
                name: "Everyday Benefits"
                short_desc: "1% fuel surcharge waiver on transactions"
              value: "Up to ₹250 per billing cycle"
            - descriptor:
                code: "TNC_LINK"
                name: "Terms & Conditions"
                short_desc: "Terms and Conditions"
              value: "https://hdfcbank.com/cc/tnc.html"

      matched: true
      recommended: true

      xinput:
        head:
          descriptor:
            name: "Know your Customer"
          index:
            min: 0
            cur: 0
            max: 0
          headings:
            - "JOURNEY_OFFLINE"

        form:
          id: "c0e857f6-15b6-4b4d-a7da-ad63b4b2e52b"
          mime_type: "application/html"
          url: "https://hdfc-cc.refo.dev/cc/form/c0e857f6-15b6-4b4d-a7da-ad63b4b2e52b"
          resubmit: false
          multiple_sumbissions: false

        required: true
