order:
  provider:
    id: "P1"

  fulfillments:
    - id: "F1"
      type: "POLICY"
      customer:
        person:
          name: "Joe Adam"
        contact:
          email: "joe.adam@abc.org"
          phone: "+91-9999999999"

  items:
    - id: "CHILD_ITEM_ID_I1"
      parent_item_id: "I1"
      add_ons:
        - id: "A1"
          quantity:
            selected:
              count: 1
      xinput:
        form:
          id: "F07"
        form_response:
          status: "SUCCESS"
          submission_id: "6ae80f7d-1fe2-4bb2-8ead-8c3c2ded9358"

  payments:
    - collected_by: "BPP"
      status: "NOT-PAID"
      type: "PRE-FULFILLMENT"
      params:
        amount: "1100"
        bank_account_number: "1800002341"
        bank_code: "SBIN0001234"
        currency: "INR"
      tags:
        - descriptor:
            code: "BUYER_FINDER_FEES"
          display: false
          list:
            - descriptor:
                code: "BUYER_FINDER_FEES_TYPE"
              value: "percent-annualized"
            - descriptor:
                code: "BUYER_FINDER_FEES_PERCENTAGE"
              value: "1"
        - descriptor:
            code: "SETTLEMENT_TERMS"
          display: false
          list:
            - descriptor:
                code: "SETTLEMENT_WINDOW"
              value: "PT60M"
            - descriptor:
                code: "SETTLEMENT_BASIS"
              value: "Delivery"
            - descriptor:
                code: "SETTLEMENT_TYPE"
              value: "upi"
            - descriptor:
                code: "DELAY_INTEREST"
              value: "2.5"
            - descriptor:
                code: "STATIC_TERMS"
              value: "https://www.icicibank.com/personal-banking/loans/personal-loan"
            - descriptor:
                code: "SETTLEMENT_AMOUNT"
              value: "400"
            - descriptor:
                code: "OFFLINE_CONTRACT"
              value: "true"
