save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  items: "$.message.order.providers[*].items[*]"
  provider_id: "$.message.order.providers[0].id"
  item: "$.message.order.providers[0].items[0]"
  loan_amount_adjustment_form: "$..form.url"