order:
  provider:
    id: "101"

  items:
    - id: "d9eb81e2-96b5-477f-98dc-8518ad60d72e"
      xinput:
        form:
          id: "0e4b4a09-d1ae-4234-8512-3f1cf31f8bc3"

        form_response:
          status: "SUCCESS"
          submission_id: "f27ab737-bd34-48c2-af73-7efe6062087f"
