intent:
  category:
    descriptor:
      code: MOTOR_INSURANCE

  provider:
    id: P1
    items:
      - id: I1
        xinput:
          form:
            id: F01
          form_response:
            status: SUCCESS
            submission_id: e9a3b4a5-10f8-42c7-b888-dbf0e2edd684

  payment:
    collected_by: BPP
    tags:
      - descriptor:
          code: BUYER_FINDER_FEES
        display: false
        list:
          - descriptor:
              code: BUYER_FINDER_FEES_TYPE
            value: percent-annualized
          - descriptor:
              code: BUYER_FINDER_FEES_PERCENTAGE
            value: "1"

      - descriptor:
          code: SETTLEMENT_TERMS
        display: false
        list:
          - descriptor:
              code: SETTLEMENT_WINDOW
            value: PT60M
          - descriptor:
              code: SETTLEMENT_BASIS
            value: Delivery
          - descriptor:
              code: DELAY_INTEREST
            value: "2.5"
          - descriptor:
              code: STATIC_TERMS
            value: "https://bap.credit.becknprotocol.io/personal-banking/loans/personal-loan"
          - descriptor:
              code: OFFLINE_CONTRACT
            value: "true"
