catalog:
  descriptor:
    name: "HDFC Bank Limited"

  providers:
    - id: "101"
      descriptor:
        name: "HDFC Bank Limited"
        images:
          - url: "https://url.com/hdfc/hdfc-sm.png"
            size_type: "sm"
          - url: "https://url.com/hdfc/hdfc-md.png"
            size_type: "md"
          - url: "https://url.com/hdfc/hdfc-lg.png"
            size_type: "lg"
        short_desc: "HDFC Bank Limited"
        long_desc: "HDFC Bank Limited"

      categories:
        - id: "10004"
          descriptor:
            code: "CARD"
            name: "Card"
        - id: "1000"
          parent_category_id: "10004"
          descriptor:
            code: "CREDIT_CARD"
            name: "Credit Card"
        - id: "1001"
          parent_category_id: "1000"
          descriptor:
            name: "Premium Cards"
            code: "PREMIUIM_CARDS"
        - id: "1002"
          parent_category_id: "1000"
          descriptor:
            name: "Travel Cards"
            code: "TRAVEL_CARDS"
        - id: "1003"
          parent_category_id: "1000"
          descriptor:
            name: "Rewards Cards"
            code: "REWARDS_CARDS"
        - id: "4"
          parent_category_id: "1000"
          descriptor:
            name: "Lifestyle Cards"
            code: "LIFESTYLE_CARDS"

      items:
        - id: "d9eb81e2-96b5-477f-98dc-8518ad60d72e"
          parent_item_id: "1001"
          descriptor:
            code: "CREDIT_CARD"
            name: "HDFC Gold Credit Card"
            short_desc: "Experience the Golden Side Of Life"
            images:
              - url: "https://url.com/hdfc/cards/hdfc-sm.png"
                size_type: "sm"
              - url: "https://url.com/hdfc/cards/hdfc-md.png"
                size_type: "md"
              - url: "https://url.com/hdfc/cards/hdfc-lg.png"
                size_type: "lg"
          category_ids:
            - "1001"

          tags:
            - descriptor:
                name: "General Information"
                code: "GENERAL_INFO"
              display: true
              list:
                - descriptor:
                    code: "WELCOME_BENEFIT"
                    name: "Welcome Benefit"
                    short_desc: "Welcome Benefit"
                  value: "Complimentary Swiggy One and MMT Black Gold membership as Welcome benefits"
                - descriptor:
                    code: "ANNUAL_FEE"
                    name: "Annual Fee"
                    short_desc: "Annual membership fee"
                  value: "1000 INR"
                - descriptor:
                    code: "JOINING_FEE"
                    name: "Joining Fee"
                    short_desc: "One-time joining fee"
                  value: "500 INR"
                - descriptor:
                    code: "REWARDS"
                    name: "Rewards"
                    short_desc: "Reward points earned on spent"
                  value: "2 Points per ₹150 spent"
                - descriptor:
                    code: "TRAVEL_BENEFITS"
                    name: "Travel Benefits"
                    short_desc: "Travel Benefits"
                  value: "2 Points per ₹150 spent"
                - descriptor:
                    code: "LIFESTYLE_BENEFITS"
                    name: "Lifestyle Benefits"
                    short_desc: "Lifestyle Benefits"
                  value: "Enjoy the exclusive 24/7 Concierge Services on your HDFC Bank Regalia Gold Credit Card. Simply call us on 1860 425 1188"
                - descriptor:
                    code: "EVERYDAY_BENEFITS"
                    name: "Everyday Benefits"
                    short_desc: "1% fuel surcharge waiver on transactions"
                  value: "Up to ₹250 per billing cycle"
                - descriptor:
                    code: "TNC_LINK"
                    name: "Terms & Conditions"
                    short_desc: "Terms and Conditions"
                  value: "https://hdfcbank.com/cc/tnc.html"

          matched: true
          recommended: true

          xinput:
            head:
              descriptor:
                name: "Customer Information"
              index:
                min: 0
                cur: 0
                max: 0
              headings:
                - "PERSONAL_INFORMATION"

            form:
              id: "0e4b4a09-d1ae-4234-8512-3f1cf31f8bc3"
              url: "https://hdfc-cc.refo.dev/cc/form/0e4b4a09-d1ae-4234-8512-3f1cf31f8bc3"
              mime_type: "text/html"
              resubmit: false
              multiple_sumbissions: false

            required: true

        - id: "418693c9-9e49-4ec2-8af9-5255f5d693fa"
          descriptor:
            name: "IndianOil HDFC Bank Credit Card"
            code: "CARD"
            short_desc: "Earn up to 50 Liters of Free fuel annually"
            images:
              - url: "https://url.com/hdfc/cards/hdfc-sm.png"
                size_type: "sm"
              - url: "https://url.com/hdfc/cards/hdfc-md.png"
                size_type: "md"
              - url: "https://url.com/hdfc/cards/hdfc-lg.png"
                size_type: "lg"

          category_ids:
            - "1002"

          tags:
            - descriptor:
                name: "General Information"
                code: "GENERAL_INFO"
              display: true
              list:
                - descriptor:
                    code: "WELCOME_BENEFIT"
                    name: "Welcome Benefit"
                    short_desc: "Welcome Benefit"
                  value: "Complimentary Swiggy One and MMT Black Gold membership as Welcome benefits"
                - descriptor:
                    code: "ANNUAL_FEE"
                    name: "Annual Fee"
                    short_desc: "Annual membership fee"
                  value: "1000 INR"
                - descriptor:
                    code: "JOINING_FEE"
                    name: "Joining Fee"
                    short_desc: "One-time joining fee"
                  value: "500 INR"
                - descriptor:
                    code: "APR"
                    name: "Annual Percentage Rate"
                    short_desc: "Annual Percentage Rate"
                  value: "20%"
                - descriptor:
                    code: "REWARDS"
                    name: "Rewards"
                    short_desc: "Reward points earned on spent"
                  value: "2 Points per ₹150 spent"
                - descriptor:
                    code: "TRAVEL_BENEFITS"
                    name: "Travel Benefits"
                    short_desc: "Travel Benefits"
                  value: "2 Points per ₹150 spent"
                - descriptor:
                    code: "LIFESTYLE_BENEFITS"
                    name: "Lifestyle Benefits"
                    short_desc: "Lifestyle Benefits"
                  value: "Enjoy the exclusive 24/7 Concierge Services on your HDFC Bank Regalia Gold Credit Card."
                - descriptor:
                    code: "EVERYDAY_BENEFITS"
                    name: "Everyday Benefits"
                    short_desc: "1% fuel surcharge waiver on transactions"
                  value: "Up to ₹250 per billing cycle"
                - descriptor:
                    code: "TNC_LINK"
                    name: "Terms & Conditions"
                    short_desc: "Terms and Conditions"
                  value: "https://hdfcbank.com/cc/tnc.html"

          matched: true
          recommended: true

          xinput:
            head:
              descriptor:
                name: "Customer Information"
              index:
                min: 0
                cur: 0
                max: 0
              headings:
                - "PERSONAL_INFORMATION"

            form:
              id: "0e4b4a09-d1ae-4234-8512-3f1cf31f8bc3"
              url: "https://hdfc-cc.refo.dev/cc/form/0e4b4a09-d1ae-4234-8512-3f1cf31f8bc3"
              mime_type: "text/html"
              resubmit: false
              multiple_sumbissions: false

            required: true

      tags:
        - descriptor:
            code: "CONTACT_INFO"
            name: "Contact Info"
          list:
            - descriptor:
                code: "GRO_NAME"
                name: "Gro name"
              value: "Rishav Singh"
            - descriptor:
                code: "GRO_EMAIL"
                name: "Gro email"
              value: "support@hdfcbank.com"
            - descriptor:
                code: "GRO_CONTACT_NUMBER"
                name: "Gro contact number"
              value: "18001600"
            - descriptor:
                code: "GRO_DESIGNATION"
                name: "Gro Designation"
              value: "Grievance Redressal Officer"
            - descriptor:
                code: "GRO_ADDRESS"
                name: "Gro Address"
              value: "Mumbai Maharashtra 400013"
            - descriptor:
                code: "CUSTOMER_SUPPORT_LINK"
                name: "Customer support link"
              value: "https://www.hdfcbank.com/personal/need-help/contact-us"
            - descriptor:
                code: "CUSTOMER_SUPPORT_CONTACT_NUMBER"
                name: "Customer support contact number"
              value: "18001600"
            - descriptor:
                code: "CUSTOMER_SUPPORT_EMAIL"
                name: "Customer support email"
              value: "loansupport@example.com"

        - descriptor:
            code: "LSP_INFO"
            name: "Lsp Info"
          list:
            - descriptor:
                code: "LSP_NAME"
                name: "Lsp name"
              value: "HDFC BANK LIMITED"
            - descriptor:
                code: "LSP_EMAIL"
                name: "Lsp email"
              value: "support@hdfcbank.com"
            - descriptor:
                code: "LSP_CONTACT_NUMBER"
                name: "Lsp contact number"
              value: "18001600"
            - descriptor:
                code: "LSP_ADDRESS"
                name: "Lsp Address"
              value: "Mumbai Maharashtra 400013"

  tags:
    - descriptor:
        code: "BPP_TERMS"
        name: "BPP Terms of Engagement"
      display: false
      list:
        - descriptor:
            code: "STATIC_TERMS"
          value: "https://bpp.credit.becknprotocol.org/personal-banking/loans/personal-loan"
        - descriptor:
            code: "OFFLINE_CONTRACT"
          value: "true"
