save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  selected_provider: "$.message.order.provider"
  selected_items: "$.message.order.items[*]"
  item_id: "$.message.order.items[*].id"
  selected_fulfillments: "$.message.order.fulfillments[*]"
  quote: "$.message.quote" 
  down_payment_form: "$..form.url"
  form_id: "$..form.id"