save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  selected_provider: "$.message.order.provider"
  selected_items: "$.message.order.items[*]"
  item: "$.message.order.items[0]"
  selected_fulfillments: "$.message.order.fulfillments[*]"
  quote: "$.message.order.quote"
  quote_id: "$.message.order.quote.id"
  consumer_information_form: "$..form.url"