order:
  items:
    - id: "CHILD_ITEM_CI1"
      parent_item_id: "I1"
      add_ons:
        - id: "A1"
          quantity:
            selected:
              count: 1
      tags:
        - descriptor:
            name: General Information
            code: GENERAL_INFO
          list:
            - descriptor:
                code: IDV_SELECTED
              value: "300000"
      xinput:
        form:
          id: "F03"
        form_response:
          status: "SUCCESS"
          submission_id: "79850933-4e41-4c76-bbe6-c5a392481226"

  provider:
    id: "P1"
