catalog:
  descriptor:
    name: ABC Insurance Ltd

  providers:
    - id: P1

      categories:
        - id: C1
          parent_category_id: C11
          descriptor:
            name: Two Wheeler Comprehensive
            code: TWO_WHEELER_COMPRIHENSIVE_INSURANCE

        - id: C2
          parent_category_id: C11
          descriptor:
            name: Two Wheeler Third Party
            code: TWO_WHEELER_THIRD_PARTY_INSURANCE

        - id: C3
          parent_category_id: C11
          descriptor:
            name: Two Wheeler Own Damage
            code: TWO_WHEELER_OWN_DAMAGE

        - id: C4
          parent_category_id: C10
          descriptor:
            name: Four Wheeler Comprehensive
            code: FOUR_WHEELER_COMPRIHENSIVE_INSURANCE

        - id: C5
          parent_category_id: C10
          descriptor:
            name: Four Wheeler Third Party
            code: FOUR_WHEELER_THIRD_PARTY_INSURANCE

        - id: C6
          parent_category_id: C10
          descriptor:
            name: Four Wheeler Own Damage
            code: FOUR_WHEELER_OWN_DAMAGE

        - id: C8
          descriptor:
            name: Motor Insurance
            code: MOTOR_INSURANCE

        - id: C10
          parent_category_id: C8
          descriptor:
            name: FOUR WHEELER
            code: FOUR_WHEELER_INSURANCE

        - id: C11
          parent_category_id: C8
          descriptor:
            name: TWO WHEELER
            code: TWO_WHEELER_INSURANCE

      descriptor:
        name: Insurance Provider Name
        short_desc: Insurance Provider Short Description
        long_desc: Insurance Provider Long Description
        images:
          - url: https://www.abcinsurance.com/content/dam/abc/india/assets/images/header/logo.png
            size_type: xs

      items:
        - id: I1
          category_ids: [C1, C2, C3]
          descriptor:
            name: 2-Wheeler 3rd Party Motor Insurance
            short_desc: 2-Wheeler 3rd Party Motor Insurance by ABC Insurance Provider
            images:
              - url: https://www.abcinsurance.com/content/dam/abc/india/assets/images/header/logo.png
                size_type: xs

          time:
            label: TENURE
            duration: P1Y

          tags:
            - descriptor:
                name: General Information
                code: GENERAL_INFO
              list:
                - { descriptor: { code: PERSONAL_ACCIDENT_COVER }, value: "10000000" }
                - { descriptor: { code: DEPRECIATION_COVER }, value: "Yes" }
                - { descriptor: { code: ROAD_SIDE_ASSISTANCE }, value: "25000" }
                - { descriptor: { code: CONSUMABLES_COVER }, value: "No" }
                - { descriptor: { code: ELECTRICAL_ACCESSORIES_COVER }, value: "0.8" }
                - { descriptor: { code: NON_ELECTRICAL_ACCESSORIES_COVER }, value: "2" }
                - { descriptor: { code: ENGINE_COVER }, value: "5" }
                - { descriptor: { code: EXTERNAL_CNG_OR_LPG_COVER }, value: "Yes" }
                - { descriptor: { code: KEY_COVER }, value: "No" }
                - { descriptor: { code: PERSONAL_BAGGAGE_COVER }, value: "50" }
                - { descriptor: { code: TYRE_COVER }, value: "50" }
                - { descriptor: { code: RETURN_TO_INVOICE }, value: "50" }
                - { descriptor: { code: PER_DAY_CASH }, value: "50" }

          add_ons:
            - id: A1
              price: { currency: INR, value: "900" }
              quantity:
                available: { count: 1 }
                maximum: { count: 1 }
              descriptor:
                name: Consumables Cover
                code: CONSUMABLES_COVER

            - id: A2
              price: { currency: INR, value: "500" }
              quantity:
                available: { count: 1 }
                maximum: { count: 1 }
              descriptor:
                name: Depreciation Cover
                code: DEPRECIATION_COVER

        - id: CHILD_ITEM_CI1
          parent_item_id: I1
          price:
            currency: INR
            value: "12531"
          category_ids: [C1, C2, C3]
          descriptor:
            name: 2-Wheeler 3rd Party Motor Insurance
            short_desc: 2-Wheeler 3rd Party Motor Insurance by ABC Insurance Provider

          time:
            label: TENURE
            duration: P1Y

      payments:
        - collected_by: BPP
          tags:
            - descriptor:
                code: BUYER_FINDER_FEES
              display: false
              list:
                - { descriptor: { code: BUYER_FINDER_FEES_TYPE }, value: percent-annualized }
                - { descriptor: { code: BUYER_FINDER_FEES_PERCENTAGE }, value: "1" }

            - descriptor:
                code: SETTLEMENT_TERMS
              display: false
              list:
                - { descriptor: { code: SETTLEMENT_WINDOW }, value: PT60M }
                - { descriptor: { code: SETTLEMENT_BASIS }, value: Delivery }
                - { descriptor: { code: DELAY_INTEREST }, value: "2.5" }
                - { descriptor: { code: MANDATORY_ARBITRATION }, value: "TRUE" }
                - { descriptor: { code: COURT_JURISDICTION }, value: New Delhi }
                - { descriptor: { code: STATIC_TERMS }, value: https://www.icicibank.com/personal-banking/loans/personal-loan }
                - { descriptor: { code: OFFLINE_CONTRACT }, value: "true" }
