order:
  id: "LOAN_LEAD_ID_OR_SIMILAR_ORDER_ID"

  provider:
    id: "PROVIDER_ID"
    descriptor:
      name: "ICICI Bank"
      short_desc: "ICICI Bank Ltd"
      long_desc: "ICICI Bank Ltd, India."
      images:
        - url: "https://www.icicibank.com/content/dam/icicibank/india/assets/images/header/logo.png"
          size_type: "sm"
    tags:
      - descriptor:
          code: "CONTACT_INFO"
        list:
          - descriptor: { code: "GRO_NAME" }
            value: "ICICI"
          - descriptor: { code: "GRO_EMAIL" }
            value: "lifeline@iciciprulife.com"
          - descriptor: { code: "GRO_CONTACT_NUMBER" }
            value: "1860 266 7766"
          - descriptor: { code: "GRO_DESIGNATION" }
            value: "Nodal Grievance Redressal Officer"
          - descriptor: { code: "GRO_ADDRESS" }
            value: "One Indiabulls centre..."
          - descriptor: { code: "CUSTOMER_SUPPORT_LINK" }
            value: "https://buy.iciciprulife.com/buy/GrievanceRedStep.htm?execution=e1s1"
          - descriptor: { code: "CUSTOMER_SUPPORT_CONTACT_NUMBER" }
            value: "1800 1080"
          - descriptor: { code: "CUSTOMER_SUPPORT_EMAIL" }
            value: "customer.care@icicibank.com"

      - descriptor:
          code: "LSP_INFO"
        list:
          - descriptor: { code: "LSP_NAME" }
            value: "ICICI_LSP"
          - descriptor: { code: "LSP_EMAIL" }
            value: "lsp@iciciprulife.com"
          - descriptor: { code: "LSP_CONTACT_NUMBER" }
            value: "1860 266 7766"
          - descriptor: { code: "LSP_ADDRESS" }
            value: "One Indiabulls centre..."

  items:
    - id: "ITEM_ID_PERSONAL_LOAN_2"
      descriptor:
        code: "PERSONAL_LOAN"
        name: "Personal Loan"
      price:
        currency: "INR"
        value: "233900"
      tags:
        - descriptor:
            code: "LOAN_INFO"
          display: true
          list:
            - descriptor: { code: "INTEREST_RATE" }
              value: "12%"
            - descriptor: { code: "TERM" }
              value: "5 months"
            - descriptor: { code: "INTEREST_RATE_TYPE" }
              value: "FIXED"
            - descriptor: { code: "APPLICATION_FEE" }
              value: "1000 INR"
            - descriptor: { code: "FORECLOSURE_FEE" }
              value: "0.5%"
            - descriptor: { code: "DELAY_PENALTY_FEE" }
              value: "5%"
            - descriptor: { code: "OTHER_PENALTY_FEE" }
              value: "1%"
            - descriptor: { code: "ANNUAL_PERCENTAGE_RATE" }
              value: "5%"
            - descriptor: { code: "REPAYMENT_FREQUENCY" }
              value: "MONTHLY"
            - descriptor: { code: "NUMBER_OF_INSTALLMENTS_OF_REPAYMENT" }
              value: "45"
            - descriptor: { code: "INSTALLMENT_AMOUNT" }
              value: "46360"
            - descriptor: { code: "TNC_LINK" }
              value: "https://icicibank.com/loan/tnc.html"
            - descriptor: { code: "COOL_OFF_PERIOD" }
              value: "PT30D"
            - descriptor: { code: "KFS_LINK" }
              value: "https://icicibank.com/loan/kfs-terms"

        - descriptor:
            code: "CONSENT_INFO"
          display: false
          list:
            - descriptor: { code: "CONSENT_HANDLER" }
              value: "d28e3a3c-1185-443a-b71e-cc1e03bb5d54"

  quote:
    id: "LOAN_LEAD_ID_OR_SIMILAR"
    price:
      currency: "INR"
      value: "233900"
    breakup:
      - title: "PRINCIPAL"
        price: { currency: "INR", value: "200000" }
      - title: "INTEREST"
        price: { currency: "INR", value: "30000" }
      - title: "PROCESSING_FEE"
        price: { currency: "INR", value: "1800" }
      - title: "INSURANCE_CHARGES"
        price: { currency: "INR", value: "500" }
      - title: "NET_DISBURSED_AMOUNT"
        price: { currency: "INR", value: "197700" }
      - title: "INSURANCE_TOTAL_FEE"
        price: { currency: "INR", value: "1100" }
      - title: "TAX"
        price: { currency: "INR", value: "100" }
    ttl: "PT15D"

  fulfillments:
    - customer:
        person: { name: "John Doe" }
        contact:
          phone: "+91-9999999999"
          email: "john.doe@example.com"
      state:
        descriptor:
          code: "CONSENT_REQUIRED"

  payments:
    - id: "PAYMENT_ID_PERSONAL_LOAN"
      type: "ON_ORDER"
      status: "NOT-PAID"
      collected_by: "BPP"
      tags:
        - descriptor: { code: "BUYER_FINDER_FEES" }
          display: false
          list:
            - descriptor: { code: "BUYER_FINDER_FEES_TYPE" }
              value: "percent-annualized"
            - descriptor: { code: "BUYER_FINDER_FEES_PERCENTAGE" }
              value: "1"

        - descriptor: { code: "SETTLEMENT_TERMS" }
          display: false
          list:
            - descriptor: { code: "SETTLEMENT_WINDOW" }
              value: "PT60M"
            - descriptor: { code: "SETTLEMENT_BASIS" }
              value: "INVOICE_RECEIPT"
            - descriptor: { code: "MANDATORY_ARBITRATION" }
              value: "TRUE"
            - descriptor: { code: "COURT_JURISDICTION" }
              value: "New Delhi"
            - descriptor: { code: "STATIC_TERMS" }
              value: "https://bpp.credit.becknprotocol.org/personal-banking/loans/personal-loan"
            - descriptor: { code: "SETTLEMENT_AMOUNT" }
              value: "1159"
            - descriptor: { code: "OFFLINE_CONTRACT" }
              value: "true"

    - type: "POST_FULFILLMENT"
      id: "INSTALLMENT_ID_PERSONAL_LOAN"
      params: { amount: "46360", currency: "INR" }
      status: "NOT-PAID"
      time:
        label: "INSTALLMENT"
        range:
          start: "2023-06-01T00:00:00.000Z"
          end: "2023-06-30T23:59:59.999Z"

  cancellation_terms:
    - fulfillment_state:
        descriptor: { code: "SANCTIONED" }
      cancellation_fee:
        percentage: "3%"
    - external_ref:
        mimetype: "text/html"
        url: "https://icicibank.com/loan/tnc.html"
    - fulfillment_state:
        descriptor: { code: "DISBURSED" }
      cancellation_fee:
        percentage: "5%"

  documents:
    - descriptor:
        code: "LOAN_AGREEMENT"
        name: "Loan Agreement Document"
      mime_type: "application/pdf"
      url: "https://lender.com/loan/loan-agreement/O1.pdf"
