order:
  provider:
    id: "101"

  items:
    - id: "d9eb81e2-96b5-477f-98dc-8518ad60d72e"
      xinput:
        form:
          id: "c0e857f6-15b6-4b4d-a7da-ad63b4b2e52b"
        form_response:
          status: "SUCCESS"
          submission_id: "79850933-4e41-4c76-bbe6-c5a392481226"

  tags:
    - descriptor:
        code: "BAP_TERMS"
        name: "BAP Terms of Engagement"
      display: false
      list:
        - descriptor:
            code: "STATIC_TERMS"
          value: "https://bap.credit.becknprotocol.io/personal-banking/loans/personal-loan"
        - descriptor:
            code: "OFFLINE_CONTRACT"
          value: "true"
