order:
  fulfillments:
    - customer:
        contact:
          email: "joe.adam@abc.org"
          phone: "+91-9999999999"
        person:
          name: "Joe Adam"

  items:
    - add_ons:
        - id: A1
          quantity:
            selected:
              count: 1
      id: CHILD_ITEM_ID_I1
      parent_item_id: I1
      xinput:
        form:
          id: F05
        form_response:
          status: SUCCESS
          submission_id: "4830c4f9-b4d3-4e58-bef5-dee80eb08478"

  provider:
    id: P1

  payments:
    - collected_by: BPP
      status: NOT-PAID
      type: PRE-FULFILLMENT
      params:
        amount: "1100"
        bank_account_number: "1800002341"
        bank_code: "SBIN0001234"
        currency: INR
      tags:
        - descriptor:
            code: BUYER_FINDER_FEES
          display: false
          list:
            - descriptor:
                code: BUYER_FINDER_FEES_TYPE
              value: "percent-annualized"
            - descriptor:
                code: BUYER_FINDER_FEES_PERCENTAGE
              value: "1"
        - descriptor:
            code: SETTLEMENT_TERMS
          display: false
          list:
            - descriptor:
                code: SETTLEMENT_WINDOW
              value: "PT60M"
            - descriptor:
                code: SETTLEMENT_BASIS
              value: "Delivery"
            - descriptor:
                code: SETTLEMENT_TYPE
              value: "upi"
            - descriptor:
                code: DELAY_INTEREST
              value: "2.5"
            - descriptor:
                code: STATIC_TERMS
              value: "https://www.icicibank.com/personal-banking/loans/personal-loan"
            - descriptor:
                code: SETTLEMENT_AMOUNT
              value: "400"
            - descriptor:
                code: OFFLINE_CONTRACT
              value: "true"
