order:
  fulfillments:
    - customer:
        contact:
          email: "joe.adam@abc.org"
          phone: "+91-9999999999"
        person:
          name: "Joe Adam"
      id: "F1"

  provider:
    id: "P1"

  items:
    - id: "CHILD_ITEM_CI1"
      parent_item_id: "I1"
      add_ons:
        - id: "A1"
          quantity:
            selected:
              count: 1
      xinput:
        form:
          id: "F06"
        form_response:
          status: "SUCCESS"
          submission_id: "52c3432c-47ed-4f60-8128-20ccce140e78"

  payments:
    - collected_by: "BPP"
      status: "NOT-PAID"
      type: "PRE-FULFILLMENT"
      params:
        amount: "12505"
        bank_account_number: "1800002341"
        bank_code: "SBIN0001234"
        currency: "INR"
      tags:
        - descriptor:
            code: "BUYER_FINDER_FEES"
          display: false
          list:
            - descriptor:
                code: "BUYER_FINDER_FEES_TYPE"
              value: "percent-annualized"
            - descriptor:
                code: "BUYER_FINDER_FEES_PERCENTAGE"
              value: "1"

        - descriptor:
            code: "SETTLEMENT_TERMS"
          display: false
          list:
            - descriptor:
                code: "SETTLEMENT_WINDOW"
              value: "PT60M"
            - descriptor:
                code: "SETTLEMENT_BASIS"
              value: "Delivery"
            - descriptor:
                code: "SETTLEMENT_TYPE"
              value: "upi"
            - descriptor:
                code: "MANDATORY_ARBITRATION"
              value: "true"
            - descriptor:
                code: "COURT_JURISDICTION"
              value: "New Delhi"
            - descriptor:
                code: "DELAY_INTEREST"
              value: "2.5"
            - descriptor:
                code: "STATIC_TERMS"
              value: "https://www.icicibank.com/personal-banking/loans/personal-loan"
            - descriptor:
                code: "SETTLEMENT_AMOUNT"
              value: "12505"
            - descriptor:
                code: "OFFLINE_CONTRACT"
              value: "true"
