save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  order: "$.message.order"
  selected_items: "$.message.order.items[*]"
  selected_fulfillments: "$.message.order.fulfillments[*]"
  selected_provider: "$.message.order.provider"
  billing: "$.message.order.billing"
  tags: "$.message.order.tags[*]"
  verification_status: "$..form.url" 